const REQ_SEARCH_LIST = 'REQ_SEARCH_LIST';
const REQ_SEARCH_LIST_SUCCESS = 'REQ_SEARCH_LIST_SUCCESS';
const REQ_SEARCH_LIST_FAILURE = 'REQ_SEARCH_LIST_FAILURE';

const REQ_SEARCH_DETAIL = 'REQ_SEARCH_DETAIL';
const REQ_SEARCH_DETAIL_SUCCESS = 'REQ_SEARCH_DETAIL_SUCCESS';
const REQ_SEARCH_DETAIL_FAILURE = 'REQ_SEARCH_DETAIL_FAILURE';

export {
  REQ_SEARCH_LIST,
  REQ_SEARCH_LIST_SUCCESS,
  REQ_SEARCH_LIST_FAILURE,
  REQ_SEARCH_DETAIL,
  REQ_SEARCH_DETAIL_SUCCESS,
  REQ_SEARCH_DETAIL_FAILURE,
};
